load("/data/users/lgladiseva/rna_seq/inregrative_analysis/Human_logitModel.RData")
test <- read.table(file="/data/users/lgladiseva/rna_seq/inregrative_analysis/novel_intragenic.dat",sep="\t",col.names=c("ID","mRNA","ORF","Fickett","Hexamer"))
test$prob <- predict(mylogit,newdata=test,type="response")
attach(test)
output <- cbind("mRNA_size"=mRNA,"ORF_size"=ORF,"Fickett_score"=Fickett,"Hexamer_score"=Hexamer,"coding_prob"=test$prob)
write.table(output,file="/data/users/lgladiseva/rna_seq/inregrative_analysis/novel_intragenic",quote=F,sep="\t",row.names=ID)
